const jwt = require("jsonwebtoken");
const config = require("../Config/Keys");
const { promisify } = require("util");
// SignIn token generator.
/**
 *
 * @returns {String,String} - Token: for authentication and ExpiredIn: The time at which the token will be expired.
 */
exports.signToken = (id, role) => {
  return jwt.sign(
    {
      id: id,
      role: role,
    },
    config.jwtSecret,
    { expiresIn: config.jwtExpiresIn }
  );
};
/**
 * Verify that the token is generated by this system.
 *
 * @param {String} token  - Authentication token provided from user.
 * @returns {String} Id /null  - if user with the provided token exists it will return user id else it will return null
 */

exports.getUserId = async (token) => {
  try {
    const decoded = await promisify(jwt.verify)(token, config.jwtSecret);
    // console.log("decoded", decoded);
    return { id: decoded.id, role: decoded.role };
  } catch (err) {
    return null;
  }
};
